# Generated by Django 3.0.3 on 2020-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkComplete',
            field=models.BooleanField(default=False),
        ),
    ]
