# Generated by Django 3.0.3 on 2020-07-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20200725_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
